npm config set init-author-name "manufosela"
npm config set init-author-email "mjfosela@gmail.com"
npm config set init-author-url "https://manufosela.es"
npm config set init-license "MIT"
npm config set init-version "1.0.0"
